### ISSUE TITLE
Switch from VM based travis-ci to container based

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#35]
VM shit runs on ubuntu 12.04, container on 14.04 but they do not have sudo. But there is a apt provider to install certain packages:

``` yaml

---
sudo: false
language: python
python:
  - "3.3"
addons:
  apt:
    packages:
      - libvirt-bin
      - python-libvirt
install:
  - pip install tox
script: tox -e testxunit
env:
  global:
    - DEBIAN_FRONTEND=noninteractive
    - PACKAGE=python-libvirt
  matrix:
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy3
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#virtapi"
  email: false
```

the needed packages are not approved yet:
https://github.com/travis-ci/apt-package-whitelist/issues/723
https://github.com/travis-ci/apt-package-whitelist/issues/2385

we can migrate when these issues are resolved
