### ISSUE TITLE
Enhance linting

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#84]
vulture can scan for [unused variables, params etc](https://prospector.landscape.io/en/latest/supported_tools.html#id8). We should clean up our codebase and integrate the tool.

**Comment by bastelfreak** [comment]
I also started a [longterm](https://github.com/virtapi/marmoset/tree/enhancelinter) branch to enhance the general linting. The current prospector.yaml:

``` yaml
die-on-tool-error: true
test-warnings: true
doc-warnings: true
ignore-paths:
  - marmoset/virt/__init__.py
uses:
  - flask
pep257:
  run: true
  disable:
    - D203
pep8:
  run: true
  full: true
pyroma:
  run: true
pylint:
  run: true
dodgy:
  run: true
mccabe:
  run: true
```

This currently finds 172 warnings, most of them missings docstrings.

**Comment by bastelfreak** [comment]
The current .prospector.yaml:

``` yaml
test-warnings: true
doc-warnings: true
ignore-paths:
  - marmoset/virt/
uses:
  - flask
pep257:
  run: true
  disable:
    - D203
pep8:
  run: true
  full: true
pyroma:
  run: true
pylint:
  run: true
  enable:
    - unused-variable
    - invalid-name
dodgy:
  run: true
mccabe:
  run: true
```

and the recommended tox.ini:

``` ini
[tox]
envlist = py3{4,5}, pypy3

[testenv]
deps =
  nose
  -rrequirements.txt

[testenv:test]
commands=nosetests

[testenv:testxunit]
commands=nosetests --with-xunit

[testenv:lint]
deps =
    {[testenv]deps}
    maxcdn
    astroid
    pylint
    prospector[with_everything]
commands =
    prospector \
    --die-on-tool-error

[testenv:sphinx]
deps =
    {[testenv]deps}
    sphinx
commands = python setup.py build_sphinx
```

we will merge the current changes into master (except for the updated prospector to keep travis green).
